# Generated by Django 4.2 on 2023-08-09 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='posted_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
